puts "Villians of this here Villain Academy, assembled!"
puts "~|------------------------------------------------|~"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Ludo Kressh"
puts "Naga Sadow"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Hush"
puts "Joffrey Baratheon"
puts "Daenerys Targaryen (I mean c'mon now, have you seen?)"
puts "Norman Bates"
puts "~|------------------------------------------------|~"
